### ISSUE TITLE
Minting issue

### ISSUE THREAD

**Issue by Buky33** [ElvenTools/elven-tools-dapp#14]
Hi, first thank you for all your projects, its really well done, your code is really clean and easy to understand.

I am trying mint a SC with the dapp, and after connecting on my devnet wallet, the console prints the following error :
Sender not allowed: erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu

Did i missed a configuration somewhere ?

Thank you for your answer

**Comment by juliancwirko** [comment]
Hard to say from only that, but I guess you try to call the Elven Tools Smart Contract by another smart contract, right? 
So something is wrong with the calls there.

You can reach me on Twitter if you want because I do not have enough information here.

**Comment by Buky33** [comment]
I just installed the dapp and started it with :
> elven-tools init-dapp
> cd testFolder
> npm i
> npm run dev
Then in the navigator (localhost:3000) i tryed to "connect" and "mint" the sample contract

It seems that it tries to buy a NFT from your sample Wallet and not from mine (connected on devnet wallet).

**Comment by juliancwirko** [comment]
If you haven't changed anything in the dapp code or configuration then it should work well the way you described, you don't even need to run npm i when using elven-tools for init 

with which provider you are trying to mint (web wallet, ledger, extension, maiar mobile)?

...I mean it should work by default with preconfigured minter smart contract

**Comment by Buky33** [comment]
Exactly what i expected to ^^

I tried to connect with the devnet wallet way.

**Comment by juliancwirko** [comment]
It's hard to say. I've done the same now, and it works. Strangely, you got the error with metachain address, maybe try with a different auth provider or clear the cache and try again.

**Comment by juliancwirko** [comment]
Wait, I think I was able to reproduce that. It is only for the web wallet provider. It stays in the wallet dashboard instead of signing the transaction. Strange, probably something changed in the logic, and I'll check that. Thanks for reporting. It should still work with other providers. @Buky33

**Comment by Buky33** [comment]
thanks for testing again, i'll try on another computer and create a maiar wallet.
I keep you in touch

**Comment by Buky33** [comment]
> Wait, I think I was able to reproduce that. It is only for the web wallet provider. It stays in the wallet dashboard instead of signing the transaction. Strange, probably something changed in the logic, and I'll check that. Thanks for reporting. It should still work with other providers. @Buky33

Exactly what i encountered.
The page is blocked because an exception is thrown (you can see it in the console).
The devnet wallet checks the data provided, and its seems to differ from the connected wallet.

**Comment by juliancwirko** [comment]
It seems to be an issue on the Elrond side, but I need to confirm. The logic hasn't changed lately, and it worked previously.

**Comment by Buky33** [comment]
The interesting part is that i still can mint directly with "elven-tools nft-minter" mint command
Maybe an issue directly on the devnet wallet

Thank you for your tests, ill keep trying next days

**Comment by juliancwirko** [comment]
Yes, this problem seems only with Web Wallet and for signing transactions.

**Comment by Buky33** [comment]
Hello,
Just to confirm that everything is ok when connecting with the maiar mobile app and minting works good 👍 well done

I checked a bit and i don't know if this helps, but i noticed that an item is created in the local storage 'walletconnect' containing account and peer info with the maiar connection, while its not created with the elrond web wallet way.

I alose noticed that the sender is not included in the transaction tx (in triggerTx method) in both cases. I assume it is automatically included by a sessions cookie or something.
Anyway its very interesting to discover all this through your devs.

++

**Comment by juliancwirko** [comment]
Hey, the problem is also on, for example, https://dapp-template.elrond.com/, which is a different implementation, so I guess this is a problem in the web wallet. Btw. a couple of developers mentioned that on the telegram dev group. I am not sure where to report that, but I'll try to figure out something.

**Comment by juliancwirko** [comment]
I think you were right. The sender should be there, which is inconsistent because other providers don't require that. Maybe there is something wrong with the last changes on web wallet architecture. The older way of calling smart contracts can't pass the sender, so I had to rewrite it.

**Comment by Buky33** [comment]
Hey,
I just noticed you committed a fix so I tried it. It works perfectly !!
You are amazing, well done.
++
