### ISSUE TITLE
Wallet connect v2

### ISSUE THREAD

**Issue by xCloiz** [ElvenTools/elven-tools-dapp#17]
Hello, with the new Maiar login update from Elrond, an upgrade of the template with this could be great :)

**Comment by juliancwirko** [comment]
Hey, could you tell me more about it? I don't see any updates in: `@elrondnetwork/erdjs-wallet-connect-provider`

**Comment by juliancwirko** [comment]
I see now, there is `"@elrondnetwork/erdjs-wallet-connect-provider": "2.1.0-beta.1",` but I couldn't find it in any official repos.

So yes, it will be updated. Thanks for the info!

**Comment by juliancwirko** [comment]
implemented
