### ISSUE TITLE
Error while trying to mint

### ISSUE THREAD

**Issue by PaulWCZ** [ElvenTools/elven-tools-dapp#21]
Hi, first of all, congrats with your work !
I have an issue when I try to mint, I got this message:
<img width="821" alt="Capture d’écran 2022-11-30 à 11 19 27" src="https://user-images.githubusercontent.com/96685330/204770734-9b024825-5f6e-4768-9fc0-f84ca1178495.png">

How to reproduce:
-Clone the dapp
-npm install
-copy the env file
-npm run dev
-try to mint

**Comment by juliancwirko** [comment]
Hi, you probably don't have any funds (xEgld) in the wallet you used for logging in, or there are problems with the devnet at the moment. There is a todo item to improve the error messages.

**Comment by PaulWCZ** [comment]
I feal, so stupid, sometimes we forget the easiest things !
Sorry for the time

**Comment by juliancwirko** [comment]
No worries, error messages are unreadable ;) I need to fix it.
